### ISSUE TITLE
Should we include code directly or as submodules

### ISSUE THREAD

**Issue by stephenhouser** [PinballY/PinballY-Addons-and-Examples#1]
I have made two example example projects, one where the code is directly in this repository and the other is a submodule that is also hosted on GitHub. This issue poses, which should we use going forward to include these add-ons and examples into this central repository.

**Comment by stephenhouser** [comment]
Pro/con of submodule link is that they link to a specific version of a repository not to the "latest".

**Comment by worksasdesigned** [comment]
i think to keep it simple:
working scripts should be directly added here.

**Comment by stephenhouser** [comment]
So it is agreed, so shall it be done!
