### ISSUE TITLE
Two Tables One Wheel Not Saving View Settings

### ISSUE THREAD

**Issue by topper-2k** [PinballY/PinballY-Addons-and-Examples#11]
Normally, when I open PinballY it automatically goes to whatever my view was the last time I had it open. So if I was looking at my Favorites list when I shut it down, it opens to my Favorites when I launch it again.

But with Two Tables One Wheel, it's always opening with "Show Alternate Tables" selected. I deselect it, close PBY, reopen, and Show Alt Tables is selected again.

Is that just me or is it happening for anyone else?

I wouldn't mind it defaulting to one state or the other. But if it has to do that, I'd prefer it not show alternate tables by default.

**Comment by stephenhouser** [comment]
What value does “custom.AlternateVersionFilterMode” have in your `Settings.txt` file? Does it change when you change the setting in PinballY and then exit?

**Comment by topper-2k** [comment]
custom.AlternateVersionFilterMode is set to 1. I opened the file in Notepad++ and opened/closed PBY a few times changing the Show Alt Versions setting each time. Sometimes custom.AlternateVersionFilterMode updates (to either 0 or 1) and sometimes it doesn't.

**Comment by topper-2k** [comment]
And sometimes it updates when it shouldn't.

**Comment by stephenhouser** [comment]
That's not good. Will look into it and see if there's something I've missed.

**Comment by topper-2k** [comment]
Am I the only one having this issue?

**Comment by Aerokii** [comment]
I'm a bit late to the party, but I've seen this issue as well. Ended up just hard-coding it in the script.

**Comment by topper-2k** [comment]
> I'm a bit late to the party, but I've seen this issue as well. Ended up just hard-coding it in the script.

Can you share how you did that?

**Comment by Aerokii** [comment]
> > I'm a bit late to the party, but I've seen this issue as well. Ended up just hard-coding it in the script.
> 
> Can you share how you did that?

Absolutely! I changed line 19 from

let alternateVersionFilterOn = optionSettings.getBool(alternateVersionFilterKey);

To

let alternateVersionFilterOn = false;

And it defaults to not showing alt tables. You can set it to true to show them by default instead.

**Comment by topper-2k** [comment]
> > > I'm a bit late to the party, but I've seen this issue as well. Ended up just hard-coding it in the script.
> > 
> > 
> > Can you share how you did that?
> 
> Absolutely! I changed line 19 from
> 
> let alternateVersionFilterOn = optionSettings.getBool(alternateVersionFilterKey);
> 
> To
> 
> let alternateVersionFilterOn = false;
> 
> And it defaults to not showing alt tables. You can set it to true to show them by default instead.

Took me a while to get back to this. I don't see let alternateVersionFilter On anywhere in the 2 tables one wheel script or in the main.js script. Where did you change that?

**Comment by topper-2k** [comment]
> > > I'm a bit late to the party, but I've seen this issue as well. Ended up just hard-coding it in the script.
> > 
> > 
> > Can you share how you did that?
> 
> Absolutely! I changed line 19 from
> 
> let alternateVersionFilterOn = optionSettings.getBool(alternateVersionFilterKey);
> 
> To
> 
> let alternateVersionFilterOn = false;
> 
> And it defaults to not showing alt tables. You can set it to true to show them by default instead.

Where did you make this change? I don't see alternateVersionFilterOn = optionSettings.getBool(alternateVersionFilterKey); anywhere in the two tables one wheel script.

**Comment by Aerokii** [comment]
Hm, you sure? I'm seeing it on line 19 here on github. 

let alternateVersionFilterOn = optionSettings.getBool(alternateVersionFilterKey);

as a direct quote from https://github.com/PinballY/PinballY-Addons-and-Examples/blob/main/two-tables-one-wheel/two-tables-one-wheel.js.

**Comment by topper-2k** [comment]
You're right! DOH! I had the wrong file open. Can't believe I didn't realize that. Thanks!

**Comment by Aerokii** [comment]
No problem, happy to help!
