### ISSUE TITLE
Animated PNG (.apng) wheels do not work

### ISSUE THREAD

**Issue by Hiylow** [PinballY/PinballY-Addons-and-Examples#12]
Need support for animated png files. filename.apng

**Comment by topper-2k** [comment]
I second this request. (Is that a thing?) Anyway,  I'd like see it too.

**Comment by stephenhouser** [comment]
This might need to be in the core PinballY program. It might be able to be done with JavaScript, but at first blush seems like it would be a total hack.

**Comment by stephenhouser** [comment]
Looks like APNG support is in the latest beta — https://github.com/mjrgh/PinballY/commit/87c82f4efcc64e59a9b4e42787500ef079c31a87
