### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TravelNVal38** [PinballY/PinballY-Addons-and-Examples#14]
Is it possible that when the tables have a alternative version that a menu pops up when you launch a game from the main PinballY wheel. Perhaps an option to turn on or off this feature for those that may just want to launch direct in to their default table. I would prefer a menu pop up so I do not have to remember what tables have alternative versions and then have to go in to the main menu to choose.

Thank you

**Comment by stephenhouser** [comment]
If I'm reading your message correctly, you do get both options, depending on which button you press to start a table. Perhaps you are looking for something more?

- Select/Enter should show the pop-up game menu with the alternate versions shown.
- Launch should launch the "default" table.

You could use a custom wheel icon for the default table to give some visual clue that it has alternate versions.
