### ISSUE TITLE
Double Wheel Graphics on Table Start

### ISSUE THREAD

**Issue by alain40** [PinballY/PinballY-Addons-and-Examples#15]
4K playfield, real DMD, 1K backglass.

When I start a table, "Loading ..." appears and a second copy of the wheel graphic appears below the current wheel graphic. The two copies remain on screen, one below the other, while loading.

**Comment by stephenhouser** [comment]
Is this a problem with PinballY or one of the addons or examples? If it is with PinballY then the issue should be entered in the issue tracker for PinballY itself -- https://github.com/mjrgh/PinballY/issues/

**Comment by alain40** [comment]
In Pinbally, sorry my mistake. Let me correct.

Alain
