### ISSUE TITLE
dispatchEvent example request

### ISSUE THREAD

**Issue by RichardL64** [PinballY/PinballY-Addons-and-Examples#21]
Can anyone help with an example of 'dispatchEvent' syntax please?

**Context**
I'm trying to fire gameInfo filterSelect when programatically changing the filter with gameinfo.setCurFilter elsewhere.
gameInfo.dispatchEvent("filterselect") doesn't do it.

**Overall context**
I want to know which filter was selected before a new one is selected - so I can filter the filter. 
(i.e. if I have 1990s filter selected. i.e. my code for top 10 would use gameList.getFilterInfo(LAST FILTER).getGames() as the basis for the new filtering rather than gameList.GetAllGames().

LAST FILTER having been set by hooking gameList filterselect.

Referencing this documentation:
http://mjrnet.org/pinscape/downloads/PinballY/Help/EventTarget.html

many thanks;

**Comment by RichardL64** [comment]
np - worked it out - please ignore :)

**Comment by stephenhouser** [comment]
Closing as resolved
